<?php
//常见问题图文回复，对应ques1-3.html
$ques = "<xml>
<ToUserName>$fromUsername</ToUserName>
<FromUserName>$toUsername</FromUserName>
<CreateTime>$time</CreateTime>
<MsgType>news</MsgType>
<ArticleCount>4</ArticleCount>
<Articles>
<item>
<Title><![CDATA[常见问题]]></Title> 
<Description><![CDATA[description1]]></Description>
<PicUrl>http://1.fswange.sinaapp.com/wenhao.jpg</PicUrl>
<Url><![CDATA[]]></Url>
</item>	
<item>
<Title><![CDATA[交通事故]]></Title> 
<Description><![CDATA[description1]]></Description>
<PicUrl>http://1.fswange.sinaapp.com/wenhao.jpg</PicUrl>
<Url>http://1.fswange.sinaapp.com/ques1.html</Url>
</item>
<item>
<Title><![CDATA[工伤事故]]></Title> 
<Description><![CDATA[description1]]></Description>
<PicUrl>http://1.fswange.sinaapp.com/wenhao.jpg</PicUrl>
<Url>http://1.fswange.sinaapp.com/ques2.html</Url>
</item>
<item>
<Title><![CDATA[职业病]]></Title> 
<Description><![CDATA[description1]]></Description>
<PicUrl>http://1.fswange.sinaapp.com/wenhao.jpg</PicUrl>
<Url>http://1.fswange.sinaapp.com/ques3.html</Url>
</item>
</Articles>
</xml>"; 
   
?>
